name: Automate Deploy to Amazon EC2 using Github actions

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          –application-name kitepaint-beta_application \
          –deployment-group-name kitepaint-beta_deployment \
          –deployment-config-name CodeDeployDefault.OneAtATime \
          –github-location repository=${{ github.repository }},commitId=${{ github.sha }}
